### ISSUE TITLE
How to add a plugin to this repo

### ISSUE THREAD

**Issue by DeathsGun** [WurstSDK-Team/Plugin-Repo#1]
# Requiements
- A project with maven
- A github account
---
1. Create a .travis.yml
```yml
language: java
script:
  - mvn -q package
after_success:
  - "git config user.email YOURUSERNAME@users.noreply.github.com"
  - "git config user.name YOURUSERNAME"
  - "git clone https://${GIT_CMD}:x-oauth-basic@github.com/WurstSDK-Team/Plugin-Repo.git Repo"
  - "mvn -q org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=$TRAVIS_BUILD_DIR/target/YOURJAR.jar -DcreateChecksum=true -DlocalRepositoryPath=$TRAVIS_BUILD_DIR/Repo/repo/"
  - "cd Repo"
  - "git add ."
  - "git commit -m 'Added latest YOURPLUGIN_NAME"
  - "git push https://${GIT_CMD}:x-oauth-basic@github.com/WurstSDK-Team/Plugin-Repo.git"
```
2. Request a key in this chat we will contact you
3. If you have the key. [Go on this website](https://travis-ci.org/) and link it with github
4. Now select your Repo and go to  settings and create a variable with  the GIT_CMD and your key as value
5. push the travis.yml 
6. youre Done!
